services:
  # Backend Server
  - type: web
    name: socialquill-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: CRYPTO_KEY
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: EMAIL_SERVICE
        sync: false
      - key: PERSPECTIVE_API_KEY
        sync: false
      - key: TEXTRAZOR_API_KEY
        sync: false
      - key: INTERFACE_API_KEY
        sync: false
      - key: PERSPECTIVE_API_DISCOVERY_URL
        value: https://commentanalyzer.googleapis.com/$discovery/rest?version=v1alpha1
      - key: TEXTRAZOR_API_URL
        value: https://api.textrazor.com/
      - key: INTERFACE_API_URL
        value: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
      - key: CLASSIFIER_API_URL
        sync: false

  # Flask Classifier Server
  - type: web
    name: socialquill-classifier
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python classifier_api.py
    rootDir: classifier_server
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Static Site
  - type: web
    name: socialquill-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: client
    envVars:
      - key: REACT_APP_API_URL
        sync: false
